@startmindmap

title CloudDisk

* <&flag>CloudDisk
** √ 用户模块
*** √ 密码登录
*** √ 邮箱注册
*** √ 用户详情
** 存储池模块
*** √ 中心存储池资源管理
**** √ 文件上传
*** 个人存储池资源管理
**** √ 文件关联存储
**** 文件列表
**** 文件移动
** 文件共享模块
*** 文件分享

center footer getcharzp

@endmindmap
